// <auto-generated />
using System;
using GainBase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GainBase.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260314201030_UpdateExerciseSeed")]
    partial class UpdateExerciseSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GainBase.Data.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "None"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Resistance Band"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Squat Rack"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Arm Curl Machine"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Arm Extension Machine"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Rowing Machine"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Parallel Bars"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Pull-up Bar"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Shoulder Press Machine"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Lateral Raises Machine"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Chest Press Machine"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Chest Fly Machine"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Back Extension Machine"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Lat Pulldown Machine"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Ab Crunch Machine"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Leg Press Machine"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Leg Extension Machine"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Leg Curl Machine"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Smith Machine"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Cable Crossover Machine"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Treadmill"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Stationary Bike"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Elliptical Trainer"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Stair Climber"
                        });
                });

            modelBuilder.Entity("GainBase.Data.Models.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("MuscleGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("MuscleGroupId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbe8aa23-04f6-43fb-993c-7ba2ba04caaa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            Description = "A compound, upper-body strength exercise. It primarily targets the pectoralis major (chest), while engaging the anterior deltoids (shoulders) and triceps brachii (back of arms) for maximal muscle growth and strength.",
                            EquipmentId = 4,
                            Instructions = "Lie flat on a bench with your eyes positioned roughly under the barbell. Place your feet flat on the floor and keep them planted for stability. Grip the bar with a pronated grip slightly wider than shoulder width, wrapping your thumbs around the bar. Retract your shoulder blades and keep them pressed into the bench while maintaining a small natural arch in your lower back. Lift the barbell out of the rack by straightening your arms and move it horizontally until it is positioned above your shoulders. Lower the bar slowly and under control toward your chest while keeping your elbows at an angle roughly between 45 and 75 degrees from your torso. Continue lowering until the bar lightly touches the middle or lower part of your chest. Press the bar upward by extending your elbows while maintaining tension through your chest, shoulders, and triceps, guiding the bar slightly back toward the starting position above your shoulders. Continue pressing until your arms are fully extended. Repeat for the desired number of repetitions, then carefully move the bar back toward the rack and secure it onto the hooks.",
                            MuscleGroupId = 1,
                            Name = "Barbell Bench Press"
                        },
                        new
                        {
                            Id = new Guid("290ed620-d909-4753-8c16-1975c6c45ff6"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            Description = "A fundamental compound leg exercise. It is widely considered the premier exercise for building lower-body size and strength, primarily targeting the quadriceps and glutes while engaging the core and back for stability.",
                            EquipmentId = 3,
                            Instructions = "Position yourself under a barbell set on a squat rack so the bar rests across your upper back on the trapezius muscles. Grip the bar with both hands slightly wider than shoulder width and pull your shoulder blades together to create a stable shelf for the bar. Lift the bar out of the rack by straightening your legs and step back until you have enough space to perform the movement. Stand with your feet approximately shoulder-width apart with your toes slightly pointed outward. Keep your chest up, back neutral, and core braced. Begin the movement by pushing your hips back and bending your knees at the same time, lowering your body in a controlled manner. Continue descending until your thighs reach at least parallel with the floor or slightly lower while keeping your heels flat on the ground. Maintain your knees tracking in the same direction as your toes and keep the bar balanced over the middle of your feet. Reverse the movement by driving through your heels and extending your hips and knees at the same time. Continue rising until you return to a fully upright standing position with your hips and knees extended. After completing the desired number of repetitions, step forward carefully and place the bar back onto the rack hooks.",
                            MuscleGroupId = 3,
                            Name = "Barbell Squat"
                        },
                        new
                        {
                            Id = new Guid("b8e967c6-7665-4cf6-ac73-245cbbfd8465"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            Description = "It primarily targets the back muscles (lats) and biceps providing immense strength and posture benefits.",
                            EquipmentId = 9,
                            Instructions = "Stand beneath a pull-up bar and grasp it with a pronated grip slightly wider than shoulder width. Hang from the bar with your arms fully extended and your body straight, keeping your legs slightly bent or crossed if needed to avoid touching the ground. Engage your core and pull your shoulder blades down and back to stabilize your shoulders. Begin the movement by pulling your body upward, driving your elbows down toward your sides while keeping your torso relatively upright. Continue pulling until your chin rises above the bar. Pause briefly at the top while maintaining control, then slowly lower your body by extending your arms until you return to the starting position with your arms fully extended. Repeat for the desired number of repetitions while maintaining controlled movement throughout.",
                            MuscleGroupId = 2,
                            Name = "Pull-Up"
                        },
                        new
                        {
                            Id = new Guid("9d6eb388-fcc9-4ae2-b624-bab179d4430f"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            Description = "A compound shoulder exercise. The machine’s fixed path makes it more stable and beginner-friendly than free-weight overhead presses. Helps improve pressing power for other upper-body exercises.",
                            EquipmentId = 10,
                            Instructions = "Sit on the shoulder press machine and adjust the seat height so the handles are positioned roughly at shoulder level when you grasp them. Place your back firmly against the backrest and keep your feet flat on the floor. Grip the handles with both hands and position your elbows slightly below or in line with your shoulders. Brace your core and keep your back in contact with the backrest throughout the movement. Press the handles upward by extending your arms until they are nearly fully straight above you without locking your elbows aggressively. Pause briefly at the top while maintaining control of the weight. Slowly lower the handles back down toward shoulder level by bending your elbows in a controlled manner. Continue lowering until the handles return to the starting position near your shoulders. Repeat the movement for the desired number of repetitions while maintaining steady and controlled motion.",
                            MuscleGroupId = 4,
                            Name = "Overhead Press"
                        },
                        new
                        {
                            Id = new Guid("ba65e859-d292-4757-ac04-2e8cf7012869"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            Description = "A static core exercise performed with bodyweight only. Planks help build endurance, enhance balance, and prevent injuries by strengthening the muscles that support the spine. They also promote better posture and can improve athletic performance.",
                            EquipmentId = 1,
                            Instructions = "Start by positioning yourself face down on the floor and place your forearms on the ground with your elbows directly under your shoulders. Extend your legs behind you and place your toes on the floor so your body is supported by your forearms and toes. Lift your body off the ground and align your head, shoulders, hips, and legs in a straight line. Keep your core engaged and your glutes slightly tightened while maintaining a neutral spine. Avoid letting your hips drop toward the floor or rise too high. Keep your neck in a neutral position by looking down toward the floor. Hold this position for the desired amount of time while maintaining steady breathing and full-body tension. When finished, gently lower your knees to the floor to exit the position.",
                            MuscleGroupId = 6,
                            Name = "Plank"
                        });
                });

            modelBuilder.Entity("GainBase.Data.Models.MuscleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("MuscleGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chest"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Back"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Legs"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shoulders"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Arms"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Core"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Full Body"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Cardio"
                        });
                });

            modelBuilder.Entity("GainBase.Data.Models.UserExercise", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("UsersExercises");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "597a3a8b-0e0d-4d45-9f0c-dd561c7b59d7",
                            Email = "seeduser@gainbase.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SEEDUSER@GAINBASE.COM",
                            NormalizedUserName = "SEEDUSER",
                            PasswordHash = "AQAAAAIAAYagAAAAENG1culb9g5JbBbFkOyKwsKYZr7Fzg64rGpiXBNgwyfIPtH1eH1lzjW01NjBED/rXQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d0bb65b5-ae2c-41fe-80e2-4e71e9803a8d",
                            TwoFactorEnabled = false,
                            UserName = "SeedUser"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GainBase.Data.Models.Exercise", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GainBase.Data.Models.Equipment", "Equipment")
                        .WithMany("Exercises")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GainBase.Data.Models.MuscleGroup", "MuscleGroup")
                        .WithMany("Exercises")
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Equipment");

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("GainBase.Data.Models.UserExercise", b =>
                {
                    b.HasOne("GainBase.Data.Models.Exercise", "Exercise")
                        .WithMany("UserExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GainBase.Data.Models.Equipment", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("GainBase.Data.Models.Exercise", b =>
                {
                    b.Navigation("UserExercises");
                });

            modelBuilder.Entity("GainBase.Data.Models.MuscleGroup", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
