// <auto-generated />
using System;
using GainBase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GainBase.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260311193608_InitialExercisesDbDesign")]
    partial class InitialExercisesDbDesign
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GainBase.Data.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "None"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Resistance Band"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Squat Rack"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Arm Curl Machine"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Arm Extension Machine"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Rowing Machine"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Parallel Bars"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Pull-up Bar"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Shoulder Press Machine"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Lateral Raises Machine"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Chest Press Machine"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Chest Fly Machine"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Back Extension Machine"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Lat Pulldown Machine"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Ab Crunch Machine"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Leg Press Machine"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Leg Extension Machine"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Leg Curl Machine"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Smith Machine"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Cable Crossover Machine"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Treadmill"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Stationary Bike"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Elliptical Trainer"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Stair Climber"
                        });
                });

            modelBuilder.Entity("GainBase.Data.Models.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("MuscleGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("MuscleGroupId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbe8aa23-04f6-43fb-993c-7ba2ba04caaa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            Description = "A compound chest exercise performed lying on a flat bench.",
                            EquipmentId = 4,
                            Instructions = "Lie on a flat bench, grip the bar slightly wider than shoulder-width, lower it to your chest, then press it back up to full arm extension.",
                            MuscleGroupId = 1,
                            Name = "Barbell Bench Press"
                        },
                        new
                        {
                            Id = new Guid("290ed620-d909-4753-8c16-1975c6c45ff6"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            Description = "A fundamental compound leg exercise using a squat rack.",
                            EquipmentId = 3,
                            Instructions = "Position the bar on your upper back, unrack it, lower your hips until thighs are parallel to the floor, then drive back up through your heels.",
                            MuscleGroupId = 3,
                            Name = "Barbell Squat"
                        },
                        new
                        {
                            Id = new Guid("b8e967c6-7665-4cf6-ac73-245cbbfd8465"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            Description = "A bodyweight back exercise performed on a pull-up bar.",
                            EquipmentId = 9,
                            Instructions = "Hang from the bar with an overhand grip, pull yourself up until your chin clears the bar, then lower yourself back down with control.",
                            MuscleGroupId = 2,
                            Name = "Pull-Up"
                        },
                        new
                        {
                            Id = new Guid("9d6eb388-fcc9-4ae2-b624-bab179d4430f"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            Description = "A compound shoulder exercise using a shoulder press machine. The machine’s fixed path makes it more stable and beginner-friendly than free-weight overhead presses. Helps improve pressing power for other upper-body exercises.",
                            EquipmentId = 10,
                            Instructions = "Sit on the machine, grip the handles at shoulder height, press upward until your arms are fully extended, then lower back down slowly.",
                            MuscleGroupId = 4,
                            Name = "Overhead Press"
                        },
                        new
                        {
                            Id = new Guid("ba65e859-d292-4757-ac04-2e8cf7012869"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            Description = "A static core exercise performed with bodyweight only.",
                            EquipmentId = 1,
                            Instructions = "Get into a forearm plank position with elbows under shoulders, keep your body in a straight line from head to heels, and hold the position while engaging your core. Try to stay in this position for as much as you can.",
                            MuscleGroupId = 6,
                            Name = "Plank"
                        });
                });

            modelBuilder.Entity("GainBase.Data.Models.MuscleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("MuscleGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chest"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Back"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Legs"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shoulders"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Arms"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Core"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Full Body"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Cardio"
                        });
                });

            modelBuilder.Entity("GainBase.Data.Models.UserExercise", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("UsersExercises");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9284cabb-ccfd-4eab-a01a-700b01dd522f",
                            Email = "seeduser@gainbase.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SEEDUSER@GAINBASE.COM",
                            NormalizedUserName = "SEEDUSER",
                            PasswordHash = "AQAAAAIAAYagAAAAEDzg6hZDZ8XPyB3fViwTmyuVM3yvOnDmZimZSUTKo39LIb06FNlhcm00Y9gufKlgOA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5ac30029-6548-4ee1-a20f-e11ab564bcdd",
                            TwoFactorEnabled = false,
                            UserName = "SeedUser"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GainBase.Data.Models.Exercise", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GainBase.Data.Models.Equipment", "Equipment")
                        .WithMany("Exercises")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GainBase.Data.Models.MuscleGroup", "MuscleGroup")
                        .WithMany("Exercises")
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Equipment");

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("GainBase.Data.Models.UserExercise", b =>
                {
                    b.HasOne("GainBase.Data.Models.Exercise", "Exercise")
                        .WithMany("UserExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GainBase.Data.Models.Equipment", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("GainBase.Data.Models.Exercise", b =>
                {
                    b.Navigation("UserExercises");
                });

            modelBuilder.Entity("GainBase.Data.Models.MuscleGroup", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
